### ISSUE TITLE
Build problem on Windows

### ISSUE THREAD

**Issue by giatgen** [microsoft/msagljs#12]
I have a build problem, which I do not know how to solve:
Could you please help me
Thank you
Giatgen

PS C:\Temp\Autolayout\msagljs-main> npm run build

> msagl-js@0.0.45 build C:\Temp\Autolayout\msagljs-main
> rm -f modules/*/*.tsbuildinfo && rm -rf moduls/*/dist && lerna run build

'rm' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! msagl-js@0.0.45 build: `rm -f modules/*/*.tsbuildinfo && rm -rf moduls/*/dist && lerna run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the msagl-js@0.0.45 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

------------------
and with "npm run publish" I get this error:

lerna ERR! yarn run build stderr:
error Command failed with exit code 1.
lerna ERR! yarn run build exited 1 in 'msagl-js'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! msagl-js@0.0.45 publish: `lerna run build && lerna publish`
npm ERR! Exit status 1

**Comment by levnach** [comment]
Sorry for the delayed response! You can try using Powers Shell, or git bash, or other unix like terminals that have "rm" command.
