### ISSUE TITLE
Disable interactions

### ISSUE THREAD

**Issue by pelikhan** [microsoft/msagljs#34]
Provide option to generate SVG with mouse/keyboard interaction.

**Comment by levnach** [comment]
@pelikhan , did you mean Provide option to generate SVG *without* mouse/keyboard interaction?

**Comment by levnach** [comment]
Or do need a button/key stroke to toggle editing?

**Comment by pelikhan** [comment]
Without any interaction, but I think you already have this one.
________________________________

**Comment by levnach** [comment]
One can press ctrl-e in the SVG window, and it disables/enables the editing. That does not work though if the editor's window is not in focus. There is property RendererSvg.layoutEditingEnabled that controls it. Maybe a button is missing to toggle the feature.
