### ISSUE TITLE
the broken links

### ISSUE THREAD

**Issue by levnach** [microsoft/msagljs#59]
How do we access the examples now?  The links are broken.
![image](https://user-images.githubusercontent.com/5377127/233422163-bd7a5bce-650e-49a9-94c4-56faaf41bb76.png)
@pelikhan

**Comment by pelikhan** [comment]
You can put those files under website/static and they will be copied as is to the deployed website

**Comment by levnach** [comment]
I added the output of the builds of the examples to website/static - but not sure how to reference the added files

**Comment by pelikhan** [comment]
try https://microsoft.github.io/msagljs/editors/msagl.html, you'll need to patch some paths

**Comment by levnach** [comment]
Sorry, I do not understand.

**Comment by pelikhan** [comment]
The content of the static folder are copied as is to the GitHub pages host; however it seems that they fail to load which is probably because they assume some paths on dependent files.
________________________________

**Comment by levnach** [comment]
Do you say it is enough to put links to this folders to msagl.html?

**Comment by pelikhan** [comment]
remove `website/static` so it will be something like `website/static/foobar` ->>  `https://microsoft.github.io/msagl/foobar`
