### ISSUE TITLE
Git & Windows issue

### ISSUE THREAD

**Issue by wvdvegt** [microsoft/msagljs#76]
FYI

In the repo there are at least 4 files that cannot be created on windows (and ruin the git use of the repo as they can't be checked out or in) due to a : (Colon) in the filename. They seem to be checked in accidently.

Example is:
`msagljs\website\static\img\undraw_start_building_re_xani.svg:Zone.Identifier`

**Comment by levnach** [comment]
I removed these files. Thank you for pointing out!
