### ISSUE TITLE
Removing @esfx dependency

### ISSUE THREAD

**Issue by aocenas** [microsoft/msagljs#86]
We have a bit of a problem with this library because part of esfx needs to be built from source, which adds quite a bit of flakiness to our CI. You can see some details in this issue https://github.com/grafana/grafana/issues/83318.

I wondered if it would be even feasible to remove it for something else as PR contribution and if not what are the reasons, ie like is it important for performance, does it implement some specific algorithms that weren't available elsewhere or is it just part of some .NET -> JS conversion defaults?

I assume this is a bit of a long shot but wanted to know if such thing would even be an option or not before getting into it more.

**Comment by levnach** [comment]
By the way, if you use msagljs for small graphs, you might try its another layout type, IPSepCola, for larger graphs.

**Comment by levnach** [comment]
I removed the dependency from esfx, and have not added any other dependencies.
Here is the new packages.
- @msagl/core@1.1.19
 - @msagl/drawing@1.1.19
 - @msagl/parser@1.1.19
 - @msagl/renderer-common@1.1.21
 - @msagl/renderer-svg@1.1.21
 - @msagl/renderer-webgl@1.1.21
lerna success published 6 packages

**Comment by aocenas** [comment]
I will take a look. Right now for bigger graphs we use D3 force based layout with some tweaks, which have better performance but makes for a layout that is more "organic" and can have lots of edge crossings so would be nice to have a better layout with similar performance for these cases.
