### ISSUE TITLE
 Module 'linked-list-typed'  is not ESM

### ISSUE THREAD

**Issue by catapop84** [microsoft/msagljs#96]
I'm using this lib in an Angular project and get this warning on production compilation

```
[WARNING] Module 'linked-list-typed' used by 'node_modules/@msagl/core/dist/layout/incremental/multipole/minimumEnclosingDisc.js' is not ESM

  CommonJS or AMD dependencies can cause optimization bailouts.
```
Hope this helps, but it's probably related to `linked-list-typed` module.

this is just a warning, the compilation and everything else works as expected.

**Comment by levnach** [comment]
Thank you for reporting it. I removed the dependency on linked-list-typed in https://github.com/microsoft/msagljs/commit/5522eb13d693813b48661818c9667c9772c60fb7.
